name          'johanek-redmine'
version       '0.0.2'
author        'johanek'
license       'Apache License, Version 2.0'
summary       'Module to install redmine'
project_page  'https://github.com/deadpixie/johanek-redmine'
description   'This module will install redmine, running behind apache and passenger, and backed by mysql or postgres. This fork is based on https://github.com/johanek/johanek-redmine to add support for PostgreSQL databases on CentOS 6.5.STILL NOT FULLY TESTED. DON'T USE IN PRODUCTIVE ENVIRONMENT! YOU HAVE BEEN WARNED.'
dependency    'puppetlabs/mysql',  '>= 2.0.0'
dependency 	   'puppetlabs/postgresql'